[versions]
#Agp
agp = "9.2.1"

# Core
coreKtx = "1.19.0"

# Lifecycle
lifecycleRuntimeKtx = "2.11.0"

# Kotlin
kotlin = "2.4.10"

# Coroutines
kotlinxCoroutinesCore = "1.11.0"

# Compose
composeBom = "2026.06.01"
activityCompose = "1.13.0"
material3Android = "1.5.0-alpha25"

[libraries]
# Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# Lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

# build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }

# ViewModel
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleRuntimeKtx" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3-android", version.ref = "material3Android" }

[bundles]
compose-core = [
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-material3",
    "androidx-activity-compose"
]

[plugins]
# Agp
android-application = { id = "com.android.application", version.ref = "agp" }

# Android library
android-library = { id = "com.android.library", version.ref = "agp" }

# Kotlin-compose
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Kotlin jvm
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

# build-logic
brbxmvi-android-application = { id = "brbxmvi.android.application" }
brbxmvi-kotlin-library = { id = "brbxmvi.kotlin.library" }
brbxmvi-android-library = { id = "brbxmvi.android.library" }